### PR TITLE
New calendar component

### PR DESCRIPTION
**Pull request by sorokinvj**
## Description
Block already booked dates on calendar, 

## New dependancy
- react-date-picker

## Screenshots
Existed booking 18-19 Oct
My-bookings-18-Oct

is blocked on new calendar component on `/dates/create`
Screenshot 2023-01-15 at 19 54 14

### CODE REVIEW

**Comment by juliencharrel** [comment]
image
Weird bug

**Comment by juliencharrel** [comment]
Maybe Add on hover a message saying "You already have a booking for these dates"
image

**Comment by sorokinvj** [comment]
> image
> 
> Weird bug

fixed

**Comment by sorokinvj** [comment]
> Maybe Add on hover a message saying "You already have a booking for these dates" image

I could also add a color stripe or any other mark on these dates: 

Screenshot 2023-01-18 at 18 57 27

@daneelminev what do you think?

**Comment by juliencharrel** [comment]
> > Maybe Add on hover a message saying "You already have a booking for these dates" image
> 
> I could also add a color stripe or any other mark on these dates:
> 
> Screenshot 2023-01-18 at 18 57 27
> 
> @daneelminev what do you think?

I don't see the hover in my branch, did you push it?

**Pull request merged**
