### PR TITLE
Gdpr cookies popup

### PR DESCRIPTION
**Pull request by sorokinvj**
Implementation of #14 

- changed standard .btn border to 1px (because it seems we use it everywhere now)
- clicking on Accept sets localStorage item to true
- clicking on Deny sets localStorage item to false

### CODE REVIEW

**Comment by daneelminev** [comment]
@sorokinvj

For footer panel shadow:

box-shadow: 0px -4px 4px rgba(0, 0, 0, 0.25), 0px -1px 18px rgba(0, 0, 0, 0.12), 0px -6px 10px rgba(0, 0, 0, 0.14);

On overlay popup - add background behind overlay:

rgba(0, 0, 0, 0.25);

https://user-images.githubusercontent.com/112096992/207037017-bc094c8f-bf27-4b00-87c7-7830f8ee01e3.mp4

**Comment by sorokinvj** [comment]
@daneelminev I added box-shadow to the popup but didn't understand about the overlay - where do you expect it to see?

**Comment by closerearth** [comment]
- Position of popup should be fixed to bottom of page so I can't scroll past it.
- Let's have a single button that says "Confirm" for now.
- Copy:
"In order to continue navigating on this website you need to accept the use of cookies."

**Comment by closerearth** [comment]
Can we make the shadow a bit less prominent? (about 50% less opacity)
And the background same as body background instead of white?

**Comment by sorokinvj** [comment]
@closerearth added border-top instead of shadow and fixed position

**Pull request merged**
