### PR TITLE
refactor: booking state

### PR DESCRIPTION
**Pull request by sorokinvj**
Refactor booking flow according to #18 
- adopt booking state to use URL params and backend GET /booking/:id
- all tasks from #18 URL section are acccomplished

### CODE REVIEW

**Comment by sorokinvj** [comment]
All other tasks from #18 related to other sections need design work and should be refined additionally, because: 
- "Non guest ready states" related tasks are hard to understand both for me and @daneelminev 
- I think we should re-design booking/:id page to be consistent with the booking flow pages
- as an idea we could drop /confirmation page and combine it with /booking/:id page

To complete all the tasks from #18 , backend should save questions and return from GET /booking/:id
Also it would be nice to save to the backend any payment errors, so we could show them either on /confirmation or on /booking/:id pages

**Comment by closerearth** [comment]
> as an idea we could drop /confirmation page and combine it with /booking/:id page --> Yes this should be done.

**Comment by sorokinvj** [comment]
> > as an idea we could drop /confirmation page and combine it with /booking/:id page --> Yes this should be done.

lets do that in a separate pr. @juliencharrel is really concerned that we don't check if we are on the right network, so I would rather do that first, while @daneelminev could polish /booking/:id page and come up with all the texts for different statuses

**Review by closerearth — APPROVED** [review]

**Comment by closerearth** [comment]
Thanks - the booking cards look great, and flow is much neater now!

**Pull request merged**
